version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=fbGiYknG2CSz
      - POSTGRES_DB=dev_db
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=joaopedro.gama0675@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ckuKJ0S1flLw
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

volumes:
  postgres-data:
  pgadmin-data:

networks:
  default:
    external:
      name: nebulosa-dev
