version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PSWD}
    ports:
      - "5433:5433"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: pg_isready -h postgres -p 5433 -U ${POSTGRES_USER} || exit 1
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    command: -p 5433
    restart: always
    networks:
      - pgadmin-network
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PSWD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5050/ || exit
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    networks:
      - pgadmin-network
      - default

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PSWD}
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PSWD}
      - PROXY_ADDRESS_FORWARDING=true
      - DB_SCHEMA=public
      - DB_VENDOR=${DB_VENDOR}
      - DB_ADDR=${DB_ADDR}
      - DB_DATABASE=${KEYCLOAK_DB}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PSWD}
    volumes:
      - "./configfiles/auth/keycloak_init.sh:/opt/jboss/startup-scripts/1.sh"
    command:
      - start-dev
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - keycloak-db
    networks:
      - pgadmin-network
      - default

  keycloak-db:
    image: postgres:11-alpine
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PSWD}
    ports:
      - "5432:5432"
    volumes:
      - "./keycloak-data:/var/lib/postgresql/data"
    healthcheck:
      test: pg_isready -U ${KEYCLOAK_DB_USER} || exit 1
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    restart: always
    networks:
      - pgadmin-network
      - default

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./configfiles/sites/development.conf:/etc/nginx/conf.d/development.conf"
      - "./configfiles/nginx-common/:/etc/nginx/nginxconfig.io/"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: service nginx status || exit 1
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    ports:
      - "80:80"
    restart:
      always
    networks:
      - pgadmin-network
      - default

volumes:
  postgres-data:
  pgadmin-data:
  keycloak-data:

networks:
  pgadmin-network:
    external: true
  default:
    external:
      name: ${NETWORK}
